### ISSUE TITLE
MAX_LENGTH is not defined in retrieval

### ISSUE THREAD

**Issue by absolute-nil** [shmsw25/FActScore#14]
factscore/retrieval.py line 70, in build_db
max_length = MAX_LENGTH - len(passages[-1])

**Comment by shmsw25** [comment]
Thank you for reporting a bug. It is fixed now. If you could pip install the package from the main branch, you'll be able to run it. We'll update the pip package soon as well.

**Comment by martiansideofthemoon** [comment]
Fixed in d768d81
