### ISSUE TITLE
Regarding human evaluation

### ISSUE THREAD

**Issue by pat-jj** [shmsw25/FActScore#29]
Hi, thanks for your great work!
To reproduce your results of error rate, is it possible for you to release the human evaluation results?
If not, could you tell which 500 entities you were using for the experiments?

**Comment by shmsw25** [comment]
Hi @pat-jj, thanks for your interest in our work. The human evaluation results are already included in the data we released. You can download it by installing factscore and then typing `python -m factscore.download_data`. Or, if preferred, you can download it directly from [our Google Drive link](https://drive.google.com/file/d/1enz1PxwxeMr4FRF9dtpCPXaZQCBejuVF/view?usp=sharing). Once you download it, check out the folder named `labeled`, and it includes human evaluation data.

**Comment by pat-jj** [comment]
I see, will check it out. Thanks a lot!
