### ISSUE TITLE
The chatgpt-based AtomicFactGenerator of FactScore sometimes abstain from answering

### ISSUE THREAD

**Issue by HillZhang1999** [shmsw25/FActScore#30]
Dear authors,

Firstly, I would like to express my gratitude for your valuable work.

I recently utilized your tool to assess the factual precision of bios generated by my LLMs. However, I have observed that when the generated bio includes toxic content, the AtomicFactGenerator based on ChatGPT consistently declines to break them down into atomic facts. I was wondering if you have any suggestions or ideas to address this issue.

Thank you once again for your remarkable contribution.

**Comment by shmsw25** [comment]
Hi @HillZhang1999 , thank you for your interest to our work, and for reporting the issue.

First, I want to clarify whether the abstention happens in the decomposition stage (AtomicFactGenerator) or the validation stage. the decomposition stage doesn't use ChatGPT - it uses InstructGPT instead, and as far as I know, InstructGPT doesn't abstain from answering. Or please let me know if you find InstructGPT still abstain from answering - we will look into this issue more closely.

If the abstention happens from validation (where we use ChatGPT), this can possibly happen. In that case, I recommend using `retrieval+llama+npm` version instead of `retrieval+ChatGPT` version. I believe it won't abstain from answering.

**Comment by HillZhang1999** [comment]
> Hi @HillZhang1999 , thank you for your interest to our work, and for reporting the issue.
> 
> First, I want to clarify whether the abstention happens in the decomposition stage (AtomicFactGenerator) or the validation stage. the decomposition stage doesn't use ChatGPT - it uses InstructGPT instead, and as far as I know, InstructGPT doesn't abstain from answering. Or please let me know if you find InstructGPT still abstain from answering - we will look into this issue more closely.
> 
> If the abstention happens from validation (where we use ChatGPT), this can possibly happen. In that case, I recommend using `retrieval+llama+npm` version instead of `retrieval+ChatGPT` version. I believe it won't abstain from answering.

Dear @shmsw25, earlier, I attempted to substitute InstructGPT with ChatGPT during the decomposition phase. This change was indeed the source of my issue, and I've resolved it by reverting to ChatGPT. Appreciate your help a lot!

I've also encountered a problem with Llama2-chat's performance recently. The response rate of Llama2-chat is quite low (around 20% for entities in unlabeled data), meaning that most responses are "I apologize, but I cannot provide a biography of a fictional character named xxx as there is no such person with this name."

I believe this could be due to the over-RLHF process, which makes Llama2-chat excessively cautious. Do you have any recommendations for addressing this low response rate for Llama2, as this model is now the most commonly used LLM backbone.

**Comment by shmsw25** [comment]
> I've also encountered a problem with Llama2-chat's performance recently. The response rate of Llama2-chat is quite low (around 20% for entities in unlabeled data), meaning that most responses are "I apologize, but I cannot provide a biography of a fictional character named xxx as there is no such person with this name."
> 
> I believe this could be due to the over-RLHF process, which makes Llama2-chat excessively cautious. Do you have any recommendations for addressing this low response rate for Llama2, as this model is now the most commonly used LLM backbone.

That is interesting. I'm not exactly sure how to overcome this issue. I guess Llama2-chat is RLHF-ed to be over-careful. Maybe you can add the instruction to encourage the model to be more likely to respond...?


> Moreover, I also observed an interesting phenomenon. When the AI assistant utters something like "hello", the extracted atomic facts may be {'atom': 'The person assisting is saying hello.', 'is_supported': False}. I believe this could potentially impact the performance.

This is interesting. During our own experiments, we found that when the prompts aren't about people bios, LMs often generate statements that are not verifiable. However, when the prompts are about people bios, it never happened, which was why our paper only focused on people bios. Based on what you said, it looks like Llama2-chat does give such statements.... You could possibly add an instruction to only generate the bio but nothing else, or add another pipeline to FActScore that checks whether the statement is verifiable or not.
